openapi: 3.0.1
info:
  title: Duocun Service API
  description: Duocun Restful API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.1 alpha
servers:
  - url: http://localhost:5007/api/accounts
    description: accounts module
  - url: http://localhost:5007/api/orders
    description: orders module
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    required: true
    in: header
