openapi: 3.0.1
info:
  title: Duocun Service API
  description: Duocuns application restful API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: http://localhost:9001/api/accounts
    description: accounts module
  - url: http://localhost:9001/api/orders
    description: orders module
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    required: true
    in: header
