openapi: 3.0.0
info:
  title: Account API
  description: Duocun api
  version: 0.0.1
servers:
  - url: http://localhost:8000/api/Accounts/G
paths:
  "/":
    patch:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: update account
      parameters:
        - name: status
          in: query
          description: A for active, I for inactive accounts, without this parameter will return all
          required: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: success,  other strings means fail
                  data:
                    $ref: "#/components/schemas/Accounts"
        400:
          description: invalid auth code
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: INVALID_CREDENTIAL
        500:
          description: server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: DATABASE_ERROR | SERVER_ERROR

  /{id}:
    get:
      security:
        - Bearer: []
      summary: return an account

      parameters:
        - name: id
          in: path
          description: account id
          required: true
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: success,  other strings means fail
                  data:
                    $ref: "#/components/schemas/Account"
        400:
          description: invalid auth code
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: INVALID_CREDENTIAL
        500:
          description: server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: DATABASE_ERROR | SERVER_ERROR

  /token/{id}:
    get:
      security:
        - Bearer: []
      summary: login app with token id, return an account object

      parameters:
        - name: id
          in: path
          description: token id of current user.
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: success,  other strings means fail
                  data:
                    $ref: "#/components/schemas/Account"
        400:
          description: invalid auth code
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: INVALID_CREDENTIAL
        500:
          description: server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: DATABASE_ERROR | SERVER_ERROR

  # "/wechat/{code}":
  #   get:
  #     tags:
  #       - Accounts
  #     summary: login by wechat (/wxLogin), return an account object
  #     parameters:
  #       - name: code
  #         in: path
  #         description: tencent auth code
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       200:
  #         description: OK
  #         content:
  #           application/json:
  #             schema:
  #               $ref: "#/components/schemas/Account"

  #       400:
  #         description: invalid auth code
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 code:
  #                   type: string
  #                   description: INVALID_CREDENTIAL
  #       500:
  #         description: server error
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 code:
  #                   type: string
  #                   description: DATABASE_ERROR | SERVER_ERROR

components:
  schemas:
    Account:
      required:
        - _id
      type: object
      properties:
        _id:
          type: string
        type:
          type: string
          description: client, merchant, driver, system, admin, inventory admin
        username:
          type: string
        phone:
          type: string
        balance:
          type: number
        realm:
          type: string
          description: wechat info
        openId:
          type: string
          description: wechat info
        sex:
          type: number
          description: wechat info
        imageurl:
          type: string
          description: wechat info
        unionid:
          type: string
          description: wechat info
        roles:
          type: string
          enum: ["super", "merchant-admin", "merchant-stuff", "driver", "user"]
        verified:
          type: boolean
        verificationCode:
          type: string
        merchants:
          type: array
          description: only type is merchant has this field 
          items:
            type: string
            description: merchant _id
        attributes:
          type: string
          description: client info

    Accounts:
      type: array
      items:
        $ref: "#/components/schemas/Account"
