openapi: 3.0.0
info:
  title: Category API
  description: Duocun api
  version: 0.0.1
severs:
  - url: http://localhost:8000/api/Categories/G
paths:
  /root:
    get:
      security:
        - Bearer: []
      summary: return a list of root categories

      parameters:
        - name: status
          in: query
          description: A for active, I for inactive categories, without this parameter will return all
          required: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                  properties:
                    code:
                      type: string
                      description: success,  other strings means fail
                    data:
                      type: object
                      $ref: "#/components/schemas/Categories"
        400:
          description: invalid auth code
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: INVALID_CREDENTIAL
        500:
          description: server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: DATABASE_ERROR | SERVER_ERROR
  /{id}:
    get:
      security:
        - Bearer: []
      summary: input my location and return the category my location belong to

      parameters:
        - name: id
          in: path
          required: true
          description: without this parameter will return null
          schema:
            type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                  properties:
                    code:
                      type: string
                      description: success,  other strings means fail
                    data:
                      type: object
                      properties:
                        category:
                          $ref: "#/components/schemas/Category"
                        subCategories:
                          type: object
                        products:
                          type: array
                          items:
                            $ref: "#/components/schemas/Product"
        400:
          description: invalid auth code
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: INVALID_CREDENTIAL
        500:
          description: server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: DATABASE_ERROR | SERVER_ERROR  
components:
  schemas:
    Echo:
      type: object
      properties:
        token:
          type: string

    Category:
      required:
        - _id
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        nameEN:
          type: string
          description: NY
        description:
          type: string
          description: optional
        descriptionEN:
          type: string
          description: optional
        type:
          type: string
          description: AppType, G for grocery, F for Food delivery 
        status:
          type: string
          description: A for active, I for inactive
        created:
          type: string
          description: create date
        modified:
          type: string
          description: modified date

    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"

    Product:
      required:
        - _id
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        nameEN:
          type: string
        description:
          type: string
        descriptionEN:
          type: string
        price:
          type: number
        cost:
          type: number
        taxRate:
          type: number
          description: eg. 13 means 13 percent
        merchantId:
          type: string
        categoryId:
          type: string
        pictures:
          type: string array
        dow:
          type: array
        status:
          type: string
          description: A for active, I for inactive