openapi: 3.0.0
info:
  title: Account API
  description: Duocun api
  version: 0.0.1
severs:
  - url: http://localhost:8000/api/Orders
paths:
  "/bulk/":
    post:
      componets:
        securitySchemes:
          bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
      security:
        - Bearer: []
      summary: save orders and add corresponding transactions, return a list of the new orders with paymentId and _id

      requestBody:
        required: true
        content:
          application/json:  
          schema:
            type: array
            items:
              type: object
              properties:

                clientId:
                  type:string
                clientName:
                  type: string
                merchantId:
                  type: string
                merchantName:
                  type: string

                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      price:
                        type: number
                      cost:
                        type: number
                      quantity:
                        type: number
                location:
                  type: object
                  properties:
                    placeId:
                      type: string
                    streetNumber:
                      type: string
                    streetName:
                      type: string
                    subLocality:
                      type: string
                    city:
                      type: string
                    province:
                      type: string
                    postalCode:
                      type: string
                    lat:
                      type: number
                    lng:
                      type: number
                  pickupTime:
                    type: string
                    description: local time, should be 10:00 for now
                  deliverDate:
                    type: string
                  deliverTime:
                    type: string
                  type:
                    type: string
                    description: G fro grocery
                  status:
                    type: string
                    description: F for Finished, T for Temp, N for New
                  paymentMethod:
                    type: string
                    description: W for wechat, CC for Credit Card, P for Prepaid, CA for CASH
                  paymentStatus:
                    type: string
                    description: P for paid, U for unpaid
                  price:
                    type: number
                  cost:
                    type: number
                  deliveryCost:
                    type: number
                  deliveryDiscount:
                    type: number
                  groupDiscount:
                    type: number
                  overRangeCharge:
                    type: number
                  total:
                    type: number
                  tax:
                    type: number
                  defaultPickupTime:
                    type: string
                    description: '' as default
                  note:
                    type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                  properties:
                    code:
                      type: string
                      description: success,  other strings means fail
                    data:
                      type: object
                      $ref: "#/components/schemas/Orders"
        400:
          description: invalid auth code
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: INVALID_CREDENTIAL
        500:
          description: server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: DATABASE_ERROR | SERVER_ERROR

  
components:
  schemas:
    Echo:
      type: object
      properties:
        token:
          type: string

    Account:
      required:
        - _id
      type: object
      properties:
        _id:
          type: string
        items:
          type: object
          description: object type
        price:
          type: number
        cost:
          type: number
        paymentMethod:
          type: string
          description: W for wechat, CC for Credit Card, P for Prepaid, CA for CASH
        paymentStatus:
          type: string
          description: P for paid, U for unpaid
        status:
          type: string
          description: F for Finished, T for Temp, N for New
        client:
          type: object
          description: account
        merchant:
          type: object
          description: account
        # merchantAccount:
        #   type: object
        #   description: account
        driver:
          type: object
          description: account
        note:
          type: string
        delivered:
          type: string
        created:
          type: string

    Orders:
      type: array
      items:
        $ref: "#/components/schemas/Order"
